### ISSUE TITLE
Update to Craft CMS 3.6 Error

### ISSUE THREAD

**Issue by dsmrt** [flipboxfactory/craft-domains#2]
```Declaration of flipbox\craft\domains\fields\Domains::inputHtml(flipbox\craft\domains\queries\DomainsQuery $query, bool $static) must be compatible with craft\base\Field::inputHtml($value, ?craft\base\ElementInterface $element = null): string```

**Comment by dsmrt** [comment]
Looks like they might have added this in 3.5: https://github.com/craftcms/cms/blob/3.5.19/CHANGELOG.md#added-15. Do we just need to rename it to not conflict with the one they added?

**Comment by nateiler** [comment]
Fixed in https://github.com/flipboxfactory/craft-domains/releases/tag/2.0.2
